##  Numpy Array Functions

In [4]:
import numpy as op
array1 = op.array([1,5,3,8,6,9,7])
print(array1)
print(type(array1))

[1 5 3 8 6 9 7]
<class 'numpy.ndarray'>


In [7]:
array2 = op.array([[1,5,9,6,4,4],[7,3,4,9,8,6]])
print(array2)

[[1 5 9 6 4 4]
 [7 3 4 9 8 6]]


In [6]:
array2.shape #numpy attribute

(2, 6)

In [4]:
array2.dtype #numpy attribute

dtype('int32')

In [5]:
array3 = op.array([[1,5,9.0,6,4],[7,3,4,9,8]])
array3


array([[1., 5., 9., 6., 4.],
       [7., 3., 4., 9., 8.]])

In [6]:
array3.dtype

dtype('float64')

In [7]:
array4 = op.array([[1,5,9,6.0,4],[7,3,4,9,8]], dtype='int32')


In [8]:
array4.dtype


dtype('int32')

In [9]:
op.zeros((9,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
op.zeros((6))

array([0., 0., 0., 0., 0., 0.])

In [11]:
op.zeros((1)).dtype

dtype('float64')

In [12]:
op.ones((7,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
op.ones((7,8)).dtype

dtype('float64')

In [14]:
op.ones((7,8)).shape

(7, 8)

In [15]:
op.empty((4,6))

array([[6.23042070e-307, 3.56043053e-307, 1.37961641e-306,
        8.90071135e-308, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
        2.22522597e-306, 1.33511018e-306, 6.23057689e-307],
       [1.86921279e-306, 8.90098127e-307, 1.78020848e-306,
        1.60219035e-306, 1.42418172e-306, 8.06609645e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 9.79107193e-307, 3.33509775e-317]])

In [16]:
op.empty((4,6)).dtype

dtype('float64')

In [17]:
array2


array([[1, 5, 9, 6, 4, 4],
       [7, 3, 4, 9, 8, 6]])

In [18]:
array1*array1 #same for + - /

array([ 1, 25,  9, 64, 36, 81, 49])

In [19]:
array1**array1 #exponent

array([        1,      3125,        27,  16777216,     46656, 387420489,
          823543])

In [20]:
1/array1

array([1.        , 0.2       , 0.33333333, 0.125     , 0.16666667,
       0.11111111, 0.14285714])

In [21]:
12**12

8916100448256

In [22]:
op.array([2**12], dtype= 'int32')

array([4096])

## slicing

In [23]:
array2


array([[1, 5, 9, 6, 4, 4],
       [7, 3, 4, 9, 8, 6]])

In [24]:
array2[4:6]

array([], shape=(0, 6), dtype=int32)

In [25]:
areray = op.array([7,3,9,1,5,8,4,2,6])

In [26]:
areray 

array([7, 3, 9, 1, 5, 8, 4, 2, 6])

In [27]:
arr = areray[4:6] #4th to before 6th and 4th position becomes zero

In [28]:
arr

array([5, 8])

In [29]:
arr[0] #4th position is zero

5

In [30]:
arr[0] =56 #4th position is zero, will be substituted by 56

In [31]:
areray 

array([ 7,  3,  9,  1, 56,  8,  4,  2,  6])

In [32]:
array7 = op.array([5,8,2,3,6,3])

In [33]:
arm = array7[2:4].copy() # copy() does not allow changws

In [34]:
arm

array([2, 3])

In [35]:
arm[0] = 7

In [36]:
array7

array([5, 8, 2, 3, 6, 3])

In [37]:
array8 = op.array([[1,3,6,4,],[7,2,9,5]])


In [38]:
array8[1,1] # 1 of 1

2

In [39]:
array8[0]

array([1, 3, 6, 4])