In [1]:
import numpy as np

In [2]:
a = np.arange(10) #creates an array from "0" to before the given range
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = np.array([12,4,3,8,6,7,59,13,11,22,23,77,66,44,41])
a

array([12,  4,  3,  8,  6,  7, 59, 13, 11, 22, 23, 77, 66, 44, 41])

In [4]:
a.shape #to know the shape

(15,)

In [5]:
c = a.reshape(5,3) # to reshape the row and column
c


array([[12,  4,  3],
       [ 8,  6,  7],
       [59, 13, 11],
       [22, 23, 77],
       [66, 44, 41]])

In [6]:
b = np.array([7,3,9,1,8,2,5,4,6])

In [7]:
b

array([7, 3, 9, 1, 8, 2, 5, 4, 6])

In [8]:
np.argsort(b) #position of the indices will be written in ascending order

array([3, 5, 1, 7, 6, 8, 0, 4, 2], dtype=int64)

In [9]:
np.argmin(b)#position of the smallest number

3

In [10]:
np.argmax(b) #position of the biggest number

2

In [11]:
np.argsort(c) #this works horizontally by default

array([[2, 1, 0],
       [1, 2, 0],
       [2, 1, 0],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [12]:
np.argsort(c, axis=0) #this works vertically

array([[1, 0, 0],
       [0, 1, 1],
       [3, 2, 2],
       [2, 3, 4],
       [4, 4, 3]], dtype=int64)

In [13]:
np.argsort(c, axis=1) #same as default

array([[2, 1, 0],
       [1, 2, 0],
       [2, 1, 0],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)